export const robots= [
    {id:1,
    name:'ist robot',
email:'unknown@gmail.com'},
{id:2,
    name:'ist robot',
email:'unknown@gmail.com'},
{id:3,
    name:'ist robot',
email:'unknown@gmail.com'},
{id:4,
    name:'ist robot',
email:'unknown@gmail.com'},
{id:5,
    name:'ist robot',
email:'unknown@gmail.com'},
{id:6,
    name:'ist robot',
email:'unknown@gmail.com'}
]